<b>TP : Partons faire un peu de shopping ! Analyse d'un listing de 10 000 chaussures vendues en ligne</b>

source du dataset : https://www.kaggle.com/datafiniti/womens-shoes-prices

Nous allons analyser un data set contenant 10 000 chaussures avec de nombreuse caractéristiques comme le prix, les couleurs disponibles, les tailles disponibles, leurs poids...

Voici une traduction de la description des colonnes principales : 
- asins : Une liste des ASIN (identificateurs d'Amazon) utilisés pour ce produit.
- brand : Le nom de marque de ce produit.
- categories : Une liste de mots-clés de catégorie utilisés pour ce produit dans plusieurs sources.
- colors : Une liste de couleurs disponibles pour ce produit.
- count : Le nombre d'unités incluses dans l'emballage du produit. Peut inclure une description de l'unité.
- dateAdded : La date à laquelle ce produit a été ajouté pour la première fois à la base de données des produits.
- dateUpdated : La date la plus récente à laquelle ce produit a été mis à jour ou vu par notre système.
- descriptions : Une liste des descriptions de ce produit provenant de diverses sources. Chaque description contient :
- dimension : La longueur, la largeur et la hauteur de ce produit. Unités incluses.
- ean : Les codes EAN de ce produit. Il peut y avoir plus d'un EAN dans la liste lorsqu'un produit a plusieurs variantes,
- financingAndLeasing : Une liste des conditions de financement ou de location associées à ce produit
- features : Une liste des caractéristiques associées à ce produit. La liste des caractéristiques peut être obtenue à partir des sections de caractéristiques spécifiques disponibles dans la liste des produits du produit.
- manufacturer : Numéro du fabricant
- merchants : Une liste des marchands qui vendent ce produit. Il s'agit généralement de marchands tiers que l'on trouve sur les sites Web de commerce électronique.
- name : dénomination du produit
- prices : Une liste de prix pour ce produit.
- primaryCategories : Une liste des catégories normalisées auxquelles ce produit appartient. Les valeurs des catégories peuvent être trouvées ici.
- quantities : Une liste des quantités disponibles pour ce produit. Les quantités indiquent combien d'unités du produit sont disponibles auprès d'une source spécifique à un moment donné.
- reviews : Une liste de commentaires pour ce produit.
- sizes : Une liste des tailles disponibles pour ce produit.
- skus : Une liste des références de ce produit. Les SKU sont typiquement spécifiques aux détaillants individuels ou aux sites Web.
- sourceURLs : Une liste d'URLs utilisées pour générer les données de ce produit.
- upc : Le code CUP de ce produit.
- websiteIDs : Une liste d'identifiants de site Web pour ce produit. Les ID de site Web sont liés à un détaillant en ligne spécifique. Il s'agit de l'identifiant unique utilisé par le site Web. Ils sont utilisés par Datafiniti lorsque d'autres identificateurs uniques ne sont pas disponibles pour un produit.
- weight : Le poids du produit. Unités incluses.

La source https://developer.datafiniti.co/docs/product-data-schema

<b> Exercices </b>

<b>Découverte du data set</b><br>
1) à l'aide de la fonction read_csv, importez entièrement le data set de enregistrez dans le dataframe 'Shoes' <br>
2) Utilisez la méthode .head() pour afficher les premières lignes <br>
3) Il y a trop de colonnes...Pour avoir une vue d'ensemble changez le paramétrage de pandas avec set_option pour afficher les 34 colonnes. Une fois cela fait, affichez à nouveau le head de la page <br>
4) On va garder uniquement les colonnes qui nous interessent. grace à la méthode de sélection de plusieurs colonnes, créez un dataframe 'ShoesLight', comprenant unique les colonnes suivantes :'id','name','dateUpdated','colors','prices.amountMax','prices.amountMin','prices.merchant'. <br>Affichez le head de ShoesLight.<br>

<b> data cleaning </b> <br>
5) A l'aide de la méthode .dtypes, consultez les types de chaque colonne. Ecrivez en markdown celles devant être corrigées et comment. <br>
6) A l'aide des méthodes .isnull, .sum() et len(), calculez le % de valeurs maquantes par colonne. Notez en markdown celles qui sont problématiques. <br>
7) Il manque trop de valeurs pour les colonnes des e-commercant et des couleurs. Retirez les du dataframe shoesLight <br>
8) A l'aide de la méthode .to_datetime, transformez la colonne 'dateUpdated'

<b> features modeling </b> <br>
9) caculez la colonne 'prices.amountAverage' en additionnant les colonnes 'prices.amountMax' et 'prices.amountMin' et en divisant par 2 <br>
10) grace à la méthode dt.weekday, créez une colonne 'dayOfweekUpdated', permettant de connaitre à partir de dateUpdated le jour de la semaine où les produits sont mis à jour

<b> data analyse </b> <br>

11) Analyser le prix moyen des chaussures avec la methode .desribe() <br>
12) Y-a-t-il de grandes différences de prix en fonction de la marque ? A l'aide des methodes groupby(), mean() et sort_values(), créez une varaible 'Luxe' contenant les 10 marques les plus chères, puis la variable 'lowCost' contenant les 10 marques les moins chères. <br>
13) grace à la méthode value_counts(), determinez le jour de la semaine où les produits sont le plus souvent mis à jour <br>
14) (optionnel) donnez le prix moyen des produits de la marque 'easy street' mis à jour un jeudi

In [10]:
import pandas as pd
shoes = pd.read_csv('Datafiniti_Womens_Shoes.csv' , sep=',')
pd.set_option('display.max_columns',35)
shoes.head()

,id,dateAdded,dateUpdated,asins,brand,categories,primaryCategories,colors,dimension,ean,imageURLs,keys,manufacturer,manufacturerNumber,name,prices.amountMax,prices.amountMin,prices.availability,prices.color,prices.condition,prices.currency,prices.dateAdded,prices.dateSeen,prices.isSale,prices.merchant,prices.offer,prices.returnPolicy,prices.shipping,prices.size,prices.sourceURLs,sizes,sourceURLs,upc,weight
0,AVpfEf_hLJeJML431ueH,2015-05-04T12:13:08Z,2018-01-29T04:38:43Z,NaN,Naturalizer,"Clothing,Shoes,Women's Shoes,All Women's Shoes...",Shoes,"Silver,Cream Watercolor Floral",NaN,NaN,https://i5.walmartimages.com/asr/861ca6cf-fa55...,"naturalizer/47147sc022,017136472311,womensnatu...",NaN,47147SC022,Naturalizer Danya Women N/S Open Toe Synthetic...,55.99,55.99,NaN,UWomens M Regular,NaN,USD,2017-03-28T11:40:25Z,"2017-03-25T09:19:24.819Z,2017-03-25T09:19:19.600Z",False,Overstock.com,NaN,NaN,NaN,S,https://www.overstock.com/Clothing-Shoes/Women...,"6W,9W,7.5W,12W,8.5M,9N,9M,9.5M,10.5M,10W,8.5W,...",https://www.walmart.com/ip/Naturalizer-Danya-W...,017136472311,NaN
1,AVpi74XfLJeJML43qZAc,2017-01-27T01:23:39Z,2018-01-03T05:21:54Z,NaN,MUK LUKS,"Clothing,Shoes,Women's Shoes,Women's Casual Sh...",Shoes,Grey,NaN,3.397705e+10,https://i5.walmartimages.com/asr/421de5d5-3a74...,"mukluks/00173650206,033977045743,muklukswomens...",Muk Luks,0017365020-6,MUK LUKS Womens Jane Suede Moccasin,47.00,35.25,In Stock,Grey,New,USD,2018-01-03T05:21:54Z,"2017-12-08T14:24:00.000Z,2017-11-01T02:52:00.000Z",True,Walmart.com,NaN,NaN,Standard,6,https://www.walmart.com/ip/MUK-LUKS-Womens-Jan...,"10,7,6,9,8",https://www.walmart.com/ip/MUK-LUKS-Womens-Jan...,033977045743,NaN
2,AVpi74XfLJeJML43qZAc,2017-01-27T01:23:39Z,2018-01-03T05:21:54Z,NaN,MUK LUKS,"Clothing,Shoes,Women's Shoes,Women's Casual Sh...",Shoes,Grey,NaN,3.397705e+10,https://i5.walmartimages.com/asr/421de5d5-3a74...,"mukluks/00173650206,033977045743,muklukswomens...",Muk Luks,0017365020-6,MUK LUKS Womens Jane Suede Moccasin,35.25,35.25,In Stock,Grey,New,USD,2017-12-06T05:02:42Z,"2017-11-10T15:11:00.000Z,2017-11-18T08:00:00.000Z",False,Slippers Dot Com,NaN,NaN,Value,6,https://www.walmart.com/ip/MUK-LUKS-Womens-Jan...,"10,7,6,9,8",https://www.walmart.com/ip/MUK-LUKS-Womens-Jan...,033977045743,NaN
3,AVpjXyCc1cnluZ0-V-Gj,2017-01-27T01:25:56Z,2018-01-04T11:52:35Z,NaN,MUK LUKS,"Clothing,Shoes,Women's Shoes,All Women's Shoes...","Shoes,Shoes",Black,6.0 in x 6.0 in x 1.0 in,3.397705e+10,https://i5.walmartimages.com/asr/950d38a5-0113...,"033977045903,muklukswomensdawnsuedescuffslippe...",Muk Luks,0017366001-6,MUK LUKS Womens Dawn Suede Scuff Slipper,24.75,24.75,In Stock,Black,New,USD,2018-01-04T11:52:35Z,2017-12-07T16:37:00.000Z,False,Slippers Dot Com,NaN,NaN,Value,6,https://www.walmart.com/ip/MUK-LUKS-Womens-Daw...,"10,7,6,9,8",https://www.walmart.com/ip/MUK-LUKS-Womens-Daw...,033977045903,NaN
4,AVphGKLPilAPnD_x1Nrm,2017-01-27T01:25:56Z,2018-01-18T03:55:18Z,NaN,MUK LUKS,"Clothing,Shoes,Women's Shoes,All Women's Shoes...",Shoes,Grey,6.0 in x 6.0 in x 1.0 in,3.397705e+10,https://i5.walmartimages.com/asr/5e137bc3-c900...,"mukluks/00173660206,033977045958,0033977045958...",NaN,0017366020-6,MUK LUKS Womens Dawn Suede Scuff Slipper,33.00,30.39,In Stock,Grey,New,USD,2017-12-04T21:35:47Z,2017-11-17T21:15:00.000Z,True,Walmart.com,NaN,NaN,Expedited,6,https://www.walmart.com/ip/MUK-LUKS-Womens-Daw...,"10,7,6,9,8",https://www.walmart.com/ip/MUK-LUKS-Womens-Daw...,033977045958,NaN

In [15]:
shoesLight = shoes[['id','name', 'brand', 'dateUpdated','colors','prices.amountMax','prices.amountMin','prices.merchant']]
shoesLight.head()

,id,name,brand,dateUpdated,colors,prices.amountMax,prices.amountMin,prices.merchant
0,AVpfEf_hLJeJML431ueH,Naturalizer Danya Women N/S Open Toe Synthetic...,Naturalizer,2018-01-29T04:38:43Z,"Silver,Cream Watercolor Floral",55.99,55.99,Overstock.com
1,AVpi74XfLJeJML43qZAc,MUK LUKS Womens Jane Suede Moccasin,MUK LUKS,2018-01-03T05:21:54Z,Grey,47.00,35.25,Walmart.com
2,AVpi74XfLJeJML43qZAc,MUK LUKS Womens Jane Suede Moccasin,MUK LUKS,2018-01-03T05:21:54Z,Grey,35.25,35.25,Slippers Dot Com
3,AVpjXyCc1cnluZ0-V-Gj,MUK LUKS Womens Dawn Suede Scuff Slipper,MUK LUKS,2018-01-04T11:52:35Z,Black,24.75,24.75,Slippers Dot Com
4,AVphGKLPilAPnD_x1Nrm,MUK LUKS Womens Dawn Suede Scuff Slipper,MUK LUKS,2018-01-18T03:55:18Z,Grey,33.00,30.39,Walmart.com

In [16]:
shoesLight.dtypes

id                   object
name                 object
brand                object
dateUpdated          object
colors               object
prices.amountMax    float64
prices.amountMin    float64
prices.merchant      object
dtype: object

In [17]:
shoesLight.isnull().sum()/len(shoesLight)

id                  0.0000
name                0.0000
brand               0.0000
dateUpdated         0.0000
colors              0.7369
prices.amountMax    0.0000
prices.amountMin    0.0000
prices.merchant     0.9565
dtype: float64

In [18]:
shoesLight = shoes[['id','name','brand', 'dateUpdated','prices.amountMax','prices.amountMin']]
shoesLight.head()

,id,name,brand,dateUpdated,prices.amountMax,prices.amountMin
0,AVpfEf_hLJeJML431ueH,Naturalizer Danya Women N/S Open Toe Synthetic...,Naturalizer,2018-01-29T04:38:43Z,55.99,55.99
1,AVpi74XfLJeJML43qZAc,MUK LUKS Womens Jane Suede Moccasin,MUK LUKS,2018-01-03T05:21:54Z,47.00,35.25
2,AVpi74XfLJeJML43qZAc,MUK LUKS Womens Jane Suede Moccasin,MUK LUKS,2018-01-03T05:21:54Z,35.25,35.25
3,AVpjXyCc1cnluZ0-V-Gj,MUK LUKS Womens Dawn Suede Scuff Slipper,MUK LUKS,2018-01-04T11:52:35Z,24.75,24.75
4,AVphGKLPilAPnD_x1Nrm,MUK LUKS Womens Dawn Suede Scuff Slipper,MUK LUKS,2018-01-18T03:55:18Z,33.00,30.39

In [19]:
shoesLight['dateUpdated'] = pd.to_datetime(shoesLight['dateUpdated'])
shoesLight['dateUpdated']

/var/folders/st/vgtwy6fs58s8t1k60x9zb2dm0000gn/T/ipykernel_19663/2257237557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shoesLight['dateUpdated'] = pd.to_datetime(shoesLight['dateUpdated'])

0      2018-01-29 04:38:43+00:00
1      2018-01-03 05:21:54+00:00
2      2018-01-03 05:21:54+00:00
3      2018-01-04 11:52:35+00:00
4      2018-01-18 03:55:18+00:00
                  ...
9995   2018-04-06 21:02:04+00:00
9996   2018-04-06 21:02:04+00:00
9997   2018-04-06 21:02:01+00:00
9998   2018-04-06 21:01:53+00:00
9999   2018-04-06 21:01:50+00:00
Name: dateUpdated, Length: 10000, dtype: datetime64[ns, UTC]

In [21]:
shoesLight['prices.amountAverage'] = (shoesLight['prices.amountMax'] + shoesLight['prices.amountMin']) / 2
shoesLight['prices.amountAverage'].head()

/var/folders/st/vgtwy6fs58s8t1k60x9zb2dm0000gn/T/ipykernel_19663/1246646314.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shoesLight['prices.amountAverage'] = (shoesLight['prices.amountMax'] + shoesLight['prices.amountMin']) / 2

0    55.990
1    41.125
2    35.250
3    24.750
4    31.695
Name: prices.amountAverage, dtype: float64

In [23]:
shoesLight['prices.amountAverage'].describe()

count    10000.000000
mean        60.177377
std         18.786193
min          5.375000
25%         49.990000
50%         56.875000
75%         67.490000
max        359.950000
Name: prices.amountAverage, dtype: float64

In [26]:
Luxe = shoesLight[['brand', 'prices.amountAverage']].groupby('brand').mean().sort_values(['prices.amountAverage'], ascending=False).head(10)
lowCost = shoesLight[['brand', 'prices.amountAverage']].groupby('brand').mean().sort_values(['prices.amountAverage'], ascending=True).head(10)

In [28]:
lowCost

                      prices.amountAverage
brand
Unbranded                         6.803333
Soft Ones                        10.950000
Faded Glory                      13.381250
Victoria K.                      15.880000
Genuine Dickies                  16.925000
Earth Spirit                     18.100000
Danskin Now                      19.740000
Riverberry                       24.990000
forever collectibles             25.000000
Mo Mo                            25.046667

In [29]:
shoesLight['dayOfweekUpdated'] = shoesLight['dateUpdated'].dt.weekday
shoesLight['dateUpdated'].dt.weekday.value_counts()

/var/folders/st/vgtwy6fs58s8t1k60x9zb2dm0000gn/T/ipykernel_19663/3867808748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shoesLight['dayOfweekUpdated'] = shoesLight['dateUpdated'].dt.weekday

dateUpdated
3    5516
0    1300
6    1052
2     911
1     606
4     332
5     283
Name: count, dtype: int64

In [31]:
shoesLight['prices.amountAverage'][(shoesLight['dayOfweekUpdated'] == 3) & (shoesLight['brand'] == 'easy street')].mean()

51.19532786885246